### ISSUE TITLE
Expo build fails for fresh/unedited solito monoropo starter

### ISSUE THREAD

**Issue by joseito-terence** [nandorojo/solito#125]
I have run the follow commands.
```
➜  npx create-solito-app@latest my-solito-app
➜  cd apps/expo 
➜  expo eas build --platform android
```

Following is the log from the eas build
```
Running 'gradlew :app:bundleRelease' in /home/expo/workingdir/build/android
Downloading https://services.gradle.org/distributions/gradle-6.9-all.zip
Unzipping /home/expo/.gradle/wrapper/dists/gradle-6.9-all/dooywd8nv05k16orzxge2b1bs/gradle-6.9-all.zip to /home/expo/.gradle/wrapper/dists/gradle-6.9-all/dooywd8nv05k16orzxge2b1bs
Set executable permissions for: /home/expo/.gradle/wrapper/dists/gradle-6.9-all/dooywd8nv05k16orzxge2b1bs/gradle-6.9/bin/gradle
Welcome to Gradle 6.9!
Here are the highlights of this release:
 - This is a small backport release.
 - Java 16 can be used to compile when used with Java toolchains
 - Dynamic versions can be used within plugin declarations
 - Native support for Apple Silicon processors
For more details see https://docs.gradle.org/6.9/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.9/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
> Configure project :expo-file-system
WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
> Configure project :expo
Using expo modules
  - expo-application (4.0.2)
  - expo-constants (13.0.2)
  - expo-error-recovery (3.0.5)
  - expo-file-system (13.1.4)
  - expo-font (10.0.5)
  - expo-keep-awake (10.0.2)
- expo-modules-core (0.6.5)
  - expo-splash-screen (0.14.2)
  - react-native-reanimated (2.3.3)
[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
Welcome to Metro!
              Fast - Scalable - Integrated
[stderr] Failed to construct transformer:  Error: Cannot parse /home/expo/.nvm/test/fast/Unit tests/mocks/project_dirs/nested-both/package.json as JSON: Unexpected end of JSON input
[stderr]     at Object.worker (/home/expo/workingdir/build/node_modules/jest-haste-map/build/worker.js:146:13)
[stderr]     at HasteMap._processFile (/home/expo/workingdir/build/node_modules/jest-haste-map/build/index.js:724:8)
[stderr]     at HasteMap._buildHasteMap (/home/expo/workingdir/build/node_modules/jest-haste-map/build/index.js:776:28)
[stderr]     at /home/expo/workingdir/build/node_modules/jest-haste-map/build/index.js:426:33
[stderr] error Cannot parse /home/expo/.nvm/test/fast/Unit tests/mocks/project_dirs/nested-both/package.json as JSON: Unexpected end of JSON input.
Error: Cannot parse /home/expo/.nvm/test/fast/Unit tests/mocks/project_dirs/nested-both/package.json as JSON: Unexpected end of JSON input
    at Object.worker (/home/expo/workingdir/build/node_modules/jest-haste-map/build/worker.js:146:13)
    at HasteMap._processFile (/home/expo/workingdir/build/node_modules/jest-haste-map/build/index.js:724:8)
    at HasteMap._buildHasteMap (/home/expo/workingdir/build/node_modules/jest-haste-map/build/index.js:776:28)
    at /home/expo/workingdir/build/node_modules/jest-haste-map/build/index.js:426:33
info Run CLI with --verbose flag for more details.
> Task :app:bundleReleaseJsAndAssets FAILED
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:bundleReleaseJsAndAssets'.
[stderr] > Process 'command 'node'' finished with non-zero exit value 1
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 2m 1s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
1 actionable task: 1 executed
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
```

**Comment by joseito-terence** [comment]
https://github.com/expo/eas-cli/issues/1276#issuecomment-1216307825 [Solution]
