### ISSUE TITLE
How do you configure tests with the Solito monorepo example?

### ISSUE THREAD

**Issue by mikefisher84** [nandorojo/solito#196]
Thanks for making this great monorepo starter. I've been trying to configure jest tests and for the life of me I can't seem to get it working. 

I would like to have some tests in `packages/app` but also some tests in `apps/expo` to verify they're working. When I configure jest in `packages/app` it works fine. However when I write tests in apps/expo that use the modules from `packages/app` it always fails with this error: 

```
 FAIL  src/app.test.tsx
  ● Test suite failed to run

    Invariant Violation: __fbBatchedBridgeConfig is not set, cannot invoke native modules

      at invariant (../../node_modules/invariant/invariant.js:40:15)
      at Object.<anonymous> (../../packages/app/node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:181:3)
      at Object.<anonymous> (../../packages/app/node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js:11:23)
```
In the test if I write `jest.mock('app", ()=>{})` the test passes just fine. 

I'm assuming this is because jest isn't correctly transpiling the code from the other packages but after searching high and low I can't seem to find a solution for this. 

Would love to see a solito example with jest testing configured. 

Thanks!

**Comment by nandorojo** [comment]
Hey, I’m actually not sure, but this would be useful! Could you check the showtime repo maybe?

**Comment by nandorojo** [comment]
Hey, so I just set up Jest in a solito app pretty easily.

I installed the `jest` dev dependencies in the root of the monorepo:

```
yarn add -D -W jest @types/jest // ..any others you use
```

And then I put a `babel.config.js` file in the root of the monorepo for jest:

```js
module.exports = function (api) {
  api.cache(true)
  return {
    presets: [
      ['@babel/preset-env', { targets: { node: 'current' } }],
      '@babel/preset-typescript',
    ],
  }
}
```

And now it works.

**Comment by nandorojo** [comment]
> However when I write tests in apps/expo that use the modules from packages/app it always fails with this error:

Maybe you could try adding a `module-resolver` to your `babel.config.js`?

```js
module.exports = function (api) {
  api.cache(true)
  return {
    presets: [
      ['@babel/preset-env', { targets: { node: 'current' } }],
      '@babel/preset-typescript',
    ],
  },
  "plugins": [
    ["module-resolver", {
      "root": ["./"],
      "alias": {
        "app/*": "./packages/app/*"
      }
    }]
  ]
}
```

**Comment by mikefisher84** [comment]
Thanks @nandorojo I did consider setting jest up at the root but what if you have an app that needs/wants a different jest config. Example `preset: 'jest-expo',` wouldn't be the right call in a React Web app. 

Also I did mess with module resolver but not that exact pattern so let me give that a shot. 

Thanks for looking at this!
