### ISSUE TITLE
Stream Error in Node 18

### ISSUE THREAD

**Issue by pmn4** [nandorojo/solito#205]
Getting an error when trying to install with node 18
```
$ npx create-solito-app@latest path/

blank template selected.

[solito] Failed to download example

 Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:393:5)
    at Unpack.<anonymous> (node:internal/streams/pipeline:352:14)
    at Unpack.emit (node:events:525:35)
    at [maybeClose] (~/.npm/_npx/a2e881e9997dfd2a/node_modules/create-solito-app/dist/index.js:22:79239)
    at Unpack.e.ondone (~/.npm/_npx/a2e881e9997dfd2a/node_modules/create-solito-app/dist/index.js:22:77780)
    at Unpack.emit (node:events:513:28)
    at [emit] (~/.npm/_npx/a2e881e9997dfd2a/node_modules/create-solito-app/dist/index.js:22:67104)
    at [maybeEnd] (~/.npm/_npx/a2e881e9997dfd2a/node_modules/create-solito-app/dist/index.js:22:68751)
    at [consumeChunk] (~/.npm/_npx/a2e881e9997dfd2a/node_modules/create-solito-app/dist/index.js:22:68815)
    at Unzip.<anonymous> (~/.npm/_npx/a2e881e9997dfd2a/node_modules/create-solito-app/dist/index.js:22:68138) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
```

fwiw, I used node 14 and it worked just fine

**Comment by timbielawski** [comment]
The issue here is with tar lib - in unpack.js

[MAYBECLOSE] () {
    if (this[ENDED] && this[PENDING] === 0) {
      this.emit('prefinish')
      this.emit('finish')
      this.emit('end')
      this.emit('close')
    }
  }
  
  should by 
  
  [MAYBECLOSE] () {
    if (this[ENDED] && this[PENDING] === 0) {
      this.emit('prefinish')
      this.emit('finish')
      this.emit('end')
    }
  }

**Comment by nandorojo** [comment]
i’ll look into it

**Comment by nandorojo** [comment]
i would accept a PR to fix this

**Comment by nandorojo** [comment]
I believe #222 fixes this

**Comment by nandorojo** [comment]
Fixed for node 18 https://github.com/nandorojo/solito/commit/10fa718aa54e5860dc02280c14389d29321629c4

```sh
npx create-solito-app@latest
```
