### ISSUE TITLE
Create Solito App @latest fails on install

### ISSUE THREAD

**Issue by Adevien** [nandorojo/solito#236]
> 
D:\Research>npx create-solito-app@latest demo
Need to install the following packages:
  create-solito-app@0.1.3
Ok to proceed? (y) y
🧑‍🎤 Creating solito app...

Creating a new solito app in demo...
demo folder created.
Copying template into demo...

blank template selected.

[solito] Failed to download example

 Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:393:5)
    at Unpack.<anonymous> (node:internal/streams/pipeline:352:14)
    at Unpack.emit (node:events:525:35)
    at [maybeClose] (C:\Users\Alex\AppData\Local\npm-cache\_npx\a2e881e9997dfd2a\node_modules\create-solito-app\dist\index.js:22:79239)
    at Unpack.e.ondone (C:\Users\Alex\AppData\Local\npm-cache\_npx\a2e881e9997dfd2a\node_modules\create-solito-app\dist\index.js:22:77780)
    at Unpack.emit (node:events:513:28)
    at [emit] (C:\Users\Alex\AppData\Local\npm-cache\_npx\a2e881e9997dfd2a\node_modules\create-solito-app\dist\index.js:22:67104)
    at [maybeEnd] (C:\Users\Alex\AppData\Local\npm-cache\_npx\a2e881e9997dfd2a\node_modules\create-solito-app\dist\index.js:22:68751)
    at [consumeChunk] (C:\Users\Alex\AppData\Local\npm-cache\_npx\a2e881e9997dfd2a\node_modules\create-solito-app\dist\index.js:22:68815)
    at Unzip.<anonymous> (C:\Users\Alex\AppData\Local\npm-cache\_npx\a2e881e9997dfd2a\node_modules\create-solito-app\dist\index.js:22:68138) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}

D:\Research>

**Comment by nandorojo** [comment]
Fixed for node 18 https://github.com/nandorojo/solito/commit/10fa718aa54e5860dc02280c14389d29321629c4
