### ISSUE TITLE
Unable to create new solito app

### ISSUE THREAD

**Issue by emdile** [nandorojo/solito#242]
I use npx create-solito-app@latest my-solito-app and i get this :

🧑‍🎤 Creating solito app...

Creating a new solito app in my-solito-app...
applau folder created.
Copying template into my-solito-app...

blank template selected.

[solito] Failed to download example

 Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:393:5)
    at Unpack.<anonymous> (node:internal/streams/pipeline:352:14)
    at Unpack.emit (node:events:525:35)
    at [maybeClose] (C:\Users\Owner\AppData\Local\npm-cache\_npx\a2e881e9997dfd2a\node_modules\create-solito-app\dist\index.js:22:79239)
    at Unpack.e.ondone (C:\Users\Owner\AppData\Local\npm-cache\_npx\a2e881e9997dfd2a\node_modules\create-solito-app\dist\index.js:22:77780)
    at Unpack.emit (node:events:513:28)
    at [emit] (C:\Users\Owner\AppData\Local\npm-cache\_npx\a2e881e9997dfd2a\node_modules\create-solito-app\dist\index.js:22:67104)
    at [maybeEnd] (C:\Users\Owner\AppData\Local\npm-cache\_npx\a2e881e9997dfd2a\node_modules\create-solito-app\dist\index.js:22:68751)
    at [consumeChunk] (C:\Users\Owner\AppData\Local\npm-cache\_npx\a2e881e9997dfd2a\node_modules\create-solito-app\dist\index.js:22:68815)
    at Unzip.<anonymous> (C:\Users\Owner\AppData\Local\npm-cache\_npx\a2e881e9997dfd2a\node_modules\create-solito-app\dist\index.js:22:68138) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}

node version: 18.12.1

**Comment by emdile** [comment]
> can you try node 16

oki. i will try  to see

**Comment by emdile** [comment]
It's work with node 16

**Comment by nandorojo** [comment]
Fixed for node 18 https://github.com/nandorojo/solito/commit/10fa718aa54e5860dc02280c14389d29321629c4
