### ISSUE TITLE
Error when deploying to vercel (routes-manifest.json" couldn't be found)

### ISSUE THREAD

**Issue by joeyscarim** [nandorojo/solito#247]
Steps I took:
1. npx create-solito-app@latest my-solito-app
2. Created repo and pushed to github
3. In vercel, create new project and import repo
4. Deploy

Deploy configuration looks like:
<img width="894" alt="Screenshot 2022-11-25 at 9 53 12 AM" src="https://user-images.githubusercontent.com/13211414/204028880-38a790f9-19dc-48a1-970c-4ea1f468e3fc.png">

Error:
```
[4/4] Building fresh packages...
--
09:43:21.273 | Done in 41.71s.
09:43:21.315 | Detected Next.js version: 13.0.1
09:43:21.316 | Running "cd ../.. && npx turbo run build --filter=next..."
09:43:22.032 | • Packages in scope:
09:43:22.032 | • Running build in 0 packages
09:43:22.032 | • Remote caching enabled
09:43:22.032 |  
09:43:22.033 | Tasks:    0 successful, 0 total
09:43:22.033 | Cached:    0 cached, 0 total
09:43:22.034 | Time:    345ms
09:43:22.034 |  
09:43:22.104 | Error: The file "/vercel/path0/apps/next/apps/next/.next/routes-manifest.json" couldn't be found. This is normally caused by a misconfiguration in your project.
```

Looks like turborepo didnt run at all, are there build and output settings that I need to manually enter?
<img width="813" alt="Screenshot 2022-11-25 at 9 55 18 AM" src="https://user-images.githubusercontent.com/13211414/204029169-20e83886-3489-4255-802a-5d30340ccab4.png">

Thank you for any help, first time turborepo user

**Comment by nandorojo** [comment]
your `filter` is wrong, it should be `next-app`

**Comment by gybeongotan** [comment]
[02:15:50.513] Cloning github.com/[username]/[private-repo](Branch: main, Commit: 0b20132)
[02:15:50.811] Previous build cache not available
[02:15:51.071] Cloning completed: 557.772ms
[02:15:51.071] Running "npx turbo-ignore"
[02:15:52.014] npx: installed 1 in 0.875s
[02:15:52.028] ≫   Using Turborepo to determine if this project is affected by the commit...
[02:15:52.028] 
[02:15:52.029] ≫   inferred "next-app" as workspace from "package.json"
[02:15:52.029] ≫   no previous deployments found for "next-app" on "main".
[02:15:52.029] ≫   falling back to HEAD^
[02:15:52.029] ≫   analyzing results of `npx turbo run build --filter=next-app...[HEAD^] --dry=json`
[02:15:54.956] ≫   exec error: Error: Command failed: npx turbo run build --filter=next-app...[HEAD^] --dry=json
[02:15:54.957]  ERROR  run failed: failed to resolve packages to run: commit HEAD^ does not exist
[02:15:54.957] 
[02:15:54.957] ≫   proceeding with deployment
[02:15:55.386] Running "vercel build"
[02:15:55.889] Vercel CLI 28.5.6
[02:15:56.188] Installing dependencies...
[02:15:56.551] yarn install v1.22.17
[02:15:56.649] [1/4] Resolving packages...
[02:15:58.103] [2/4] Fetching packages...
[02:16:10.307] warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
[02:16:31.461] [3/4] Linking dependencies...
[02:16:31.464] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > expo-app > react-native@0.69.5" has incorrect peer dependency "react@18.0.0".
[02:16:31.465] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > expo-app > tailwindcss@3.1.3" has unmet peer dependency "postcss@^8.0.9".
[02:16:31.465] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > @expo/next-adapter@4.0.12" has incorrect peer dependency "next@^11".
[02:16:31.465] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > @expo/next-adapter@4.0.12" has unmet peer dependency "react@^17".
[02:16:31.465] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > @expo/next-adapter@4.0.12" has unmet peer dependency "react-native-web@^0.17.0".
[02:16:31.466] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > autoprefixer@10.4.7" has unmet peer dependency "postcss@^8.1.0".
[02:16:31.466] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > next-fonts@1.5.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[02:16:31.466] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > next-images@1.8.4" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[02:16:31.466] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > @react-navigation/native@6.0.10" has unmet peer dependency "react@*".
[02:16:31.467] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > @react-navigation/native@6.0.10" has unmet peer dependency "react-native@*".
[02:16:31.467] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > @react-navigation/native-stack@6.6.2" has unmet peer dependency "react@*".
[02:16:31.467] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > @react-navigation/native-stack@6.6.2" has unmet peer dependency "react-native@*".
[02:16:31.467] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > @react-navigation/native-stack@6.6.2" has unmet peer dependency "react-native-safe-area-context@>= 3.0.0".
[02:16:31.467] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > @react-navigation/native-stack@6.6.2" has unmet peer dependency "react-native-screens@>= 3.0.0".
[02:16:31.467] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > nativewind@2.0.9" has unmet peer dependency "tailwindcss@~3".
[02:16:31.468] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > expo-app > expo-splash-screen > @expo/prebuild-config@5.0.3" has unmet peer dependency "expo-modules-autolinking@>=0.8.1".
[02:16:31.468] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > expo-app > react-native-screens > react-freeze@1.0.0" has incorrect peer dependency "react@^17.0.0".
[02:16:31.468] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > next-fonts > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[02:16:31.468] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > next-fonts > url-loader@4.1.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[02:16:31.468] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > @react-navigation/native > @react-navigation/core@6.2.1" has unmet peer dependency "react@*".
[02:16:31.468] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > @react-navigation/native-stack > @react-navigation/elements@1.3.3" has unmet peer dependency "react@*".
[02:16:31.469] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > @react-navigation/native-stack > @react-navigation/elements@1.3.3" has unmet peer dependency "react-native@*".
[02:16:31.469] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > @react-navigation/native-stack > @react-navigation/elements@1.3.3" has unmet peer dependency "react-native-safe-area-context@>= 3.0.0".
[02:16:31.469] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > moti > framer-motion@6.5.1" has unmet peer dependency "react@>=16.8 || ^17.0.0 || ^18.0.0".
[02:16:31.469] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > app > moti > framer-motion@6.5.1" has unmet peer dependency "react-dom@>=16.8 || ^17.0.0 || ^18.0.0".
[02:16:31.469] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > expo-app > react-native > react-native-codegen > jscodeshift@0.13.1" has unmet peer dependency "@babel/preset-env@^7.1.6".
[02:16:31.470] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > @expo/next-adapter > @expo/webpack-config > expo-pwa@0.0.123" has unmet peer dependency "expo@*".
[02:16:31.470] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > @expo/next-adapter > babel-preset-expo > metro-react-native-babel-preset@0.64.0" has unmet peer dependency "@babel/core@*".
[02:16:31.476] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > next@13.0.1" has unmet peer dependency "react@^18.2.0".
[02:16:31.476] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > next@13.0.1" has unmet peer dependency "react-dom@^18.2.0".
[02:16:31.476] warning "workspace-aggregator-e9f6a1aa-e213-4bac-970d-949cbed04377 > next-app > next > styled-jsx@5.1.0" has unmet peer dependency "react@>= 16.8.0 || 17.x.x || ^18.0.0-0".
[02:17:04.874] [4/4] Building fresh packages...
[02:17:05.440] success Saved lockfile.
[02:17:05.443] Done in 68.90s.
[02:17:05.490] Detected Next.js version: 13.0.1
[02:17:05.491] Running "cd ../.. && npx turbo run build --filter=next-app"
[02:17:06.425] • Packages in scope: next-app
[02:17:06.425] • Running build in 1 packages
[02:17:06.425] • Remote computation caching enabled
[02:17:06.769] next-app:build: cache miss, executing d3b02b009ed82db3
[02:17:07.072] next-app:build: yarn run v1.22.17
[02:17:07.100] next-app:build: $ next build
[02:17:07.849] next-app:build: error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
[02:17:07.853] next-app:build: 
[02:17:07.853] next-app:build: > Build error occurred
[02:17:07.855] next-app:build: Error: Cannot find module './plugins/swc_plugin_reanimated.wasm'
[02:17:07.857] next-app:build: Require stack:
[02:17:07.857] next-app:build: - /vercel/path0/apps/next/next.config.js
[02:17:07.857] next-app:build:     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
[02:17:07.857] next-app:build:     at mod._resolveFilename (/vercel/path0/node_modules/next/dist/build/webpack/require-hook.js:23:32)
[02:17:07.857] next-app:build:     at Function.resolve (node:internal/modules/cjs/helpers:109:19)
[02:17:07.858] next-app:build:     at Object.<anonymous> (/vercel/path0/apps/next/next.config.js:23:27)
[02:17:07.858] next-app:build:     at Module._compile (node:internal/modules/cjs/loader:1159:14)
[02:17:07.858] next-app:build:     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
[02:17:07.858] next-app:build:     at Module.load (node:internal/modules/cjs/loader:1037:32)
[02:17:07.858] next-app:build:     at Module._load (node:internal/modules/cjs/loader:878:12)
[02:17:07.858] next-app:build:     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
[02:17:07.858] next-app:build:     at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
[02:17:07.858] next-app:build:   code: 'MODULE_NOT_FOUND',
[02:17:07.858] next-app:build:   requireStack: [ '/vercel/path0/apps/next/next.config.js' ]
[02:17:07.858] next-app:build: }
[02:17:07.875] next-app:build: error Command failed with exit code 1.
[02:17:07.875] next-app:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[02:17:07.889] next-app:build: ERROR: command finished with error: command (/vercel/path0/apps/next) yarn run build exited (1)
[02:17:07.889] command (/vercel/path0/apps/next) yarn run build exited (1)
[02:17:07.889] 
[02:17:07.889]  Tasks:    0 successful, 1 total
[02:17:07.889] Cached:    0 cached, 1 total
[02:17:07.890]   Time:    1.937s 
[02:17:07.890] 
[02:17:07.914] Error: Command "cd ../.. && npx turbo run build --filter=next-app" exited with 1

**Comment by nandorojo** [comment]
not sure what this is about

ERROR  run failed: failed to resolve packages to run: commit HEAD^ does not exist
[02:15:54.957]

**Comment by nandorojo** [comment]
have you not pushed to a master branch or something

**Comment by gyongph** [comment]
I just followed the instant deployment and it was automatically committed to my repo.

**Comment by nandorojo** [comment]
what if you remove the custom build script

**Comment by joeyscarim** [comment]
thank you. updating the filter fixed my issue
