### ISSUE TITLE
Integrating Solito into Create-T3-Turbo

### ISSUE THREAD

**Issue by galacoder** [nandorojo/solito#377]
Dear Fernando,

I am reaching out to you as I am facing some difficulties in integrating Solito into Create-T3-Turbo.  I would appreciate your guidance in resolving this issue.

Project Repository: https://github.com/galacoder/create-t3-turbo-solito.git

I have attempted several methods to incorporate Solito into Create-T3-Turbo, but all of my efforts have been unsuccessful. Specifically, I have encountered problems with the configuration and setup, which have prevented a seamless integration.

If you could kindly take a look at my repository and provide guidance on how to properly integrate Solito, I would be grateful.

If you require any additional information or clarification, please do not hesitate to reach out. I am eager to learn from your expertise and successfully implement Solito into my project.

Thank you in advance for your time and assistance. I am looking forward to hearing from you soon.

Nextjs error
```
error - ../../node_modules/@babel/runtime/helpers/assertThisInitialized.js
Module parse failed: Cannot use 'import.meta' outside a module (40:16)
|                 // still a Refresh Boundary later.
|                 // @ts-ignore importMeta is replaced in the loader
>                 import.meta.webpackHot.accept();
|                 // This field is set when the previous version of this module was a
|                 // Refresh Boundary, letting us know we need to check for invalidation or

Import trace for requested module:
../../node_modules/@babel/runtime/helpers/assertThisInitialized.js
../../node_modules/next-auth/core/errors.js
../../node_modules/next-auth/utils/logger.js
../../node_modules/next-auth/react/index.js
```

Expo error
```
iOS Bundling failed 13ms
index.tsx: [BABEL] /Users/sangle/dev/action/projects/aeonbook/apps/mobile/index.tsx: require() of ES Module /Users/sangle/dev/action/projects/aeonbook/packages/core/design/tailwind/theme.js from /Users/sangle/dev/action/projects/aeonbook/apps/mobile/tailwind.config.js not supported.
theme.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename theme.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/sangle/dev/action/projects/aeonbook/packages/core/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
 (While processing: "/Users/sangle/dev/action/projects/aeonbook/node_modules/nativewind/babel.js")
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/sangle/dev/action/projects/aeonbook/packages/core/design/tailwind/theme.js from /Users/sangle/dev/action/projects/aeonbook/apps/mobile/tailwind.config.js not supported.
theme.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename theme.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/sangle/dev/action/projects/aeonbook/packages/core/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/Users/sangle/dev/action/projects/aeonbook/apps/mobile/tailwind.config.js:3:19)
    at default_1 (/Users/sangle/dev/action/projects/aeonbook/node_modules/nativewind/dist/babel/index.js:38:28)
    at sync (/Users/sangle/dev/action/projects/aeonbook/node_modules/@babel/core/lib/gensync-utils/async.js:31:25)
    at sync (/Users/sangle/dev/action/projects/aeonbook/node_modules/gensync/index.js:182:19)
    at /Users/sangle/dev/action/projects/aeonbook/node_modules/gensync/index.js:210:24
    at Generator.next (<anonymous>)
    at /Users/sangle/dev/action/projects/aeonbook/node_modules/@babel/core/lib/config/full.js:181:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/sangle/dev/action/projects/aeonbook/node_modules/@babel/core/lib/gensync-utils/async.js:21:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/Users/sangle/dev/action/projects/aeonbook/node_modules/gensync/index.js:251:28)
    at Function.sync (/Users/sangle/dev/action/projects/aeonbook/node_modules/gensync/index.js:89:14)
    at sync (/Users/sangle/dev/action/projects/aeonbook/node_modules/@babel/core/lib/gensync-utils/async.js:62:25)
    at sync (/Users/sangle/dev/action/projects/aeonbook/node_modules/gensync/index.js:182:19)
    at onFirstPause (/Users/sangle/dev/action/projects/aeonbook/node_modules/gensync/index.js:210:24)
    at Generator.next (<anonymous>)
    at cachedFunction (/Users/sangle/dev/action/projects/aeonbook/node_modules/@babel/core/lib/config/caching.js:52:46)
    at cachedFunction.next (<anonymous>)
    at loadPluginDescriptor (/Users/sangle/dev/action/projects/aeonbook/node_modules/@babel/core/lib/config/full.js:260:42)
    at loadPluginDescriptor.next (<anonymous>)
    at loadPluginDescriptors (/Users/sangle/dev/action/projects/aeonbook/node_modules/@babel/core/lib/config/full.js:129:33)
    at loadPluginDescriptors.next (<anonymous>)
    at /Users/sangle/dev/action/projects/aeonbook/node_modules/@babel/core/lib/config/full.js:157:21
    at Generator.next (<anonymous>)
    at loadFullConfig (/Users/sangle/dev/action/projects/aeonbook/node_modules/@babel/core/lib/config/full.js:141:5)
    at loadFullConfig.next (<anonymous>)
    at parse (/Users/sangle/dev/action/projects/aeonbook/node_modules/@babel/core/lib/parse.js:21:45)
    at parse.next (<anonymous>)
    at evaluateSync (/Users/sangle/dev/action/projects/aeonbook/node_modules/gensync/index.js:251:28)
    at sync (/Users/sangle/dev/action/projects/aeonbook/node_modules/gensync/index.js:89:14)
    at stopHiding - secret - don't use this - v1 (/Users/sangle/dev/action/projects/aeonbook/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:46:12)
    at parseSync (/Users/sangle/dev/action/projects/aeonbook/node_modules/@babel/core/lib/parse.js:41:72)
    at Object.transform (/Users/sangle/dev/action/projects/aeonbook/node_modules/metro-react-native-babel-transformer/src/index.js:194:11)
    at transformJSWithBabel (/Users/sangle/dev/action/projects/aeonbook/node_modules/metro-transform-worker/src/index.js:360:45)
    at Object.transform (/Users/sangle/dev/action/projects/aeonbook/node_modules/metro-transform-worker/src/index.js:518:18)
    at transformFile (/Users/sangle/dev/action/projects/aeonbook/node_modules/metro/src/DeltaBundler/Worker.flow.js:73:36)
    at Object.transform (/Users/sangle/dev/action/projects/aeonbook/node_modules/metro/src/DeltaBundler/Worker.flow.js:48:10)
    at execFunction (/Users/sangle/dev/action/projects/aeonbook/node_modules/jest-worker/build/workers/processChild.js:137:17)
    at execHelper (/Users/sangle/dev/action/projects/aeonbook/node_modules/jest-worker/build/workers/processChild.js:116:5)
    at execMethod (/Users/sangle/dev/action/projects/aeonbook/node_modules/jest-worker/build/workers/processChild.js:120:5)
    at process.messageListener (/Users/sangle/dev/action/projects/aeonbook/node_modules/jest-worker/build/workers/processChild.js:38:7)
```

**Comment by nandorojo** [comment]
could you pull your code into a solito starter instead?

**Comment by galacoder** [comment]
I tried that approach at first but I couldn't make it work for like a day. Then I switched to bring solito into create-t3-turbo :(

**Comment by nandorojo** [comment]
hm, the starters do work though. i wonder what library caused issues

**Comment by galacoder** [comment]
I wanted to reach out regarding an issue I encountered while trying to use your repository.

I was able to get the project to work by installing expo, nativewind, solito, and moti one by one :)

However, I am encountering an issue with moti. Despite trying to install it according to both your solito example and moti documentation, it does not seem to be working properly.

I was wondering if you could provide any guidance or assistance in resolving this issue. Any help would be greatly appreciated.

Thank you for your time and consideration.

Please advise!

Here is the error code I am receiving:

On browser
```
Unhandled Runtime Error
TypeError: Cannot convert undefined or null to object

Call Stack
Function.keys
<anonymous>
keys
../node_modules/react-native-reanimated/lib/module/reanimated2/js-reanimated/index.js (19:22)
updates
../node_modules/react-native-reanimated/lib/module/reanimated2/UpdateProps.js (17:23)
Set.forEach
<anonymous>
forEach
../node_modules/react-native-reanimated/lib/module/reanimated2/UpdateProps.js (16:25)
sharableViewDescriptors
../node_modules/react-native-reanimated/lib/module/createAnimatedComponent.js (522:22)
worklet
../node_modules/react-native-reanimated/lib/module/reanimated2/mappers.js (86:15)
run
node_modules/next/dist/compiled/setimmediate/setImmediate.js (1:447)
runIfPresent
node_modules/next/dist/compiled/setimmediate/setImmediate.js (1:663)
onGlobalMessage
node_modules/next/dist/compiled/setimmediate/setImmediate.js (1:1165)
```

Console
```
event - compiled successfully in 57 ms (220 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 2.3s (1997 modules)
"transform" style array value is deprecated. Use space-separated string functions, e.g., "scaleX(2) rotateX(15deg)".
selectable prop is deprecated. Use styles.userSelect.
accessibilityRole is deprecated. Use role.
```

**Comment by derek-primumco** [comment]
@galacoder Just a guess, but you may need react-native-reanimated (latest, version 3) and to be using a dev client for Expo (i.e. not Expo Go).

These issues tend to be impossible to debug, so the advice is almost always to start with with one of the working starter repos and then add your own code to it. There are a lot of moving parts with the shared code, Next.js transpile modules, etc.

Regarding integrating Solito into `create-t3-turbo`, I'd also love to see that, but you'd probably have to do the same thing (integrate tRPC piece-by-piece into the Solito starter, instead of installing Solito in the T3 app). If you can post a minimally reproducible repo, it would greatly help for debugging.

**Comment by galacoder** [comment]
Hello @derek-primumco,

React-native-reanimated is latest on my repo.

I was able to successfully test Solito with create-t3-turbo and it is working as expected.

Additionally, I replaced Prisma with Drizzle ORM and that is also working fine.

However, the only issue that I am encountering is with moti, which does not seem to be working properly even after installing it according to the Solito example and moti documentation.

Here is the link to the repository for your reference: https://github.com/galacoder/create-t3-turbo-solito.git

Take a look and would love to hear from you.

**Comment by derek-primumco** [comment]
@galacoder Nothing jumps out at me. I see you have `moti` in the `transpileModules` section of the Next.js config file and have it installed in both `package.json` files (`apps/web` and `packages/core`).

Maybe @nandorojo will have some insight.

**Comment by nandorojo** [comment]
i need more info, what doesn't work with moti?

**Comment by nandorojo** [comment]
why is next config .mjs? is that valid? also, why is there an empty string in transpilePackages?

**Comment by nandorojo** [comment]
can you try changing the config for next to a .js file and use module.exports = to be safe?

**Comment by nandorojo** [comment]
Do you have reanimated 3.0.2+? That's required. And you'll need to use an expo dev client instead of expo go.

**Comment by nandorojo** [comment]
Hey guys, I wonder if upgrading to Expo sdk 49 would fix some of these issues, since reanimated 3.3 now works in Expo Go with SDK 49.

**Comment by nandorojo** [comment]
also, `expo start -c` (or `expo start --dev-client -c` often fixes this stuff for me, or `yarn cache clean` in the root followed by `yarn`.
