### ISSUE TITLE
`contentPosition` prop being passed to DOM

### ISSUE THREAD

**Issue by sarat1669** [nandorojo/solito#400]
Adding the `contentPosition` property raises a warning

```tsx
<SolitoImage alt="Tribe" fill contentPosition="top center" src="/assets/tribe.webp" />
```

```
Warning: React does not recognize the `contentPosition` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `contentposition` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at img
    at eval (webpack-internal:///../../node_modules/next/dist/client/image.js:229:11)
    at eval (webpack-internal:///../../node_modules/next/dist/client/image.js:320:11)
    at SolitoImage (webpack-internal:///../../node_modules/solito/build/image/expo/image.web.js:20:108)
```

**Comment by nandorojo** [comment]
Please upgrade to 3.2.8

**Comment by sarat1669** [comment]
I'm using tamagui
