### ISSUE TITLE
tailwind starter template fails dependencies installation 

### ISSUE THREAD

**Issue by gepp4** [nandorojo/solito#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

The command `npx create-solito-app@latest my-solito-app -t with-tailwind` fails during `yarn install` with the following error message: 

```
      throw new UsageError(`Unsupported package manager specification (${raw})`);
            ^

UsageError: Unsupported package manager specification (bun@1.1.18)
    at parseSpec (C:\Users\AntoninoGargiulo\scoop\apps\nodejs-lts\20.15.1\node_modules\corepack\dist\lib\corepack.cjs:23258:13)
    at loadSpec (C:\Users\AntoninoGargiulo\scoop\apps\nodejs-lts\20.15.1\node_modules\corepack\dist\lib\corepack.cjs:23316:11)
    at async Engine.findProjectSpec (C:\Users\AntoninoGargiulo\scoop\apps\nodejs-lts\20.15.1\node_modules\corepack\dist\lib\corepack.cjs:23490:22)
    at async Engine.executePackageManagerRequest (C:\Users\AntoninoGargiulo\scoop\apps\nodejs-lts\20.15.1\node_modules\corepack\dist\lib\corepack.cjs:23542:24)
    at async Object.runMain (C:\Users\AntoninoGargiulo\scoop\apps\nodejs-lts\20.15.1\node_modules\corepack\dist\lib\corepack.cjs:24235:5) {
  clipanion: { type: 'usage' }
}

Node.js v20.15.1
[solito] error installing node_modules with yarn
 yarnpkg exited with non-zero code: 1
```

### Expected Behavior

The scaffolding should complete without errors and the both `yarn dev` and `yarn native` should run without getting errors.

### Steps To Reproduce

Run the command to scaffold the tailwind template project `npx create-solito-app@latest my-solito-app -t with-tailwind`

### Versions

```markdown
- Solito: installation failed
- Next.js: 14.2.5
- Expo: 51.0.23
- React Native: 0.72.4
```

**Comment by nandorojo** [comment]
I think this was fixed
